version: '3.9'

networks:
  main_syntax_network:

volumes:
  static:
  media:

services:
  redis_syntax:
    container_name: ${REDIS_HOST}
    hostname: ${REDIS_HOST}
    image: redis:latest
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
    volumes:
      - ./redis.conf:/usr/local/etc/redis.conf
    networks:
      - main_syntax_network

  syntax_app:
    build: .
    hostname: syntax_project
    container_name: hipet_syntax_container
    restart: always
    command: sh -c "export DJANGO_PORT=${DJANGO_PORT} &&
                    python3 entrypoint.py"
    depends_on:
      - redis_syntax
    networks:
      - main_syntax_network
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    volumes:
      - .:/code/
      - ./media:/code/media
      - ./static:/code/static

  nginx_syntax:
    image: nginx:latest
    hostname: nginx_syntax
    container_name: nginx_syntax_container
    command: nginx -g 'daemon off;'
    restart: always
    depends_on:
      - syntax_app
    expose:
      - "80"
    ports:
      - "80:80"
    networks:
      - main_syntax_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./media:/code/media
      - ./static:/code/static
